// Temario completo del sitio. Fuente única de verdad: el sitio se dibuja a partir de aquí.
// Orden progresivo: cada unidad y lección asume solo lo visto antes.
// Para un nuevo idioma: copiar este archivo como temario.<idioma>.js y traducir los textos.

window.TEMARIO = [
  {
    id: 'matematicas',
    nombre: 'Matemáticas',
    descripcion: 'De contar y repartir a resolver ecuaciones, medir el mundo y entender los datos.',
    color: '#60A5FA',
    unidades: [
      { titulo: 'Aritmética', archivo: 'lecciones/matematicas/aritmetica.js', lecciones: [
        'Números naturales y valor posicional',
        'Suma y resta',
        'Multiplicación y división',
        'Jerarquía de operaciones',
        'Divisibilidad, números primos, MCD y mcm',
        'Números enteros: los negativos',
        'Fracciones: qué son y cómo compararlas',
        'Operaciones con fracciones',
        'Números decimales',
        'Porcentajes',
        'Razones y proporciones',
        'Regla de tres',
        'Potencias y raíces',
        'Notación científica',
      ]},
      { titulo: 'Álgebra', archivo: 'lecciones/matematicas/algebra.js', lecciones: [
        'Lenguaje algebraico: de palabras a símbolos',
        'Expresiones algebraicas y términos semejantes',
        'Operaciones con polinomios',
        'Productos notables (incluye el trinomio cuadrado perfecto)',
        'Factorización',
        'Ecuaciones de primer grado',
        'Desigualdades',
        'Sistemas de ecuaciones 2×2',
        'Ecuaciones de segundo grado',
        'Leyes de los exponentes y radicales',
        'Fracciones algebraicas',
      ]},
      { titulo: 'Funciones', archivo: 'lecciones/matematicas/funciones.js', lecciones: [
        'Qué es una función',
        'El plano cartesiano y las gráficas',
        'Función lineal y pendiente',
        'Función cuadrática',
        'Función exponencial: crecimiento y decaimiento',
        'Logaritmos',
      ]},
      { titulo: 'Geometría', archivo: 'lecciones/matematicas/geometria.js', lecciones: [
        'Puntos, rectas y ángulos',
        'Triángulos y sus propiedades',
        'Teorema de Pitágoras',
        'Polígonos y perímetros',
        'Áreas de figuras planas',
        'El círculo y la circunferencia',
        'Cuerpos geométricos y volumen',
        'Semejanza y congruencia',
        'Transformaciones: traslación, rotación y simetría',
      ]},
      { titulo: 'Trigonometría', archivo: 'lecciones/matematicas/trigonometria.js', lecciones: [
        'Razones trigonométricas: seno, coseno y tangente',
        'Resolver triángulos rectángulos',
        'Ley de senos y ley de cosenos',
        'El círculo unitario',
        'Identidades trigonométricas básicas',
      ]},
      { titulo: 'Geometría analítica', archivo: 'lecciones/matematicas/geometria-analitica.js', lecciones: [
        'Distancia y punto medio',
        'La recta y su ecuación',
        'La circunferencia',
        'La parábola',
        'Elipse e hipérbola',
      ]},
      { titulo: 'Estadística y probabilidad', archivo: 'lecciones/matematicas/estadistica.js', lecciones: [
        'Recolectar y organizar datos',
        'Tablas de frecuencia',
        'Gráficas: barras, pastel e histogramas',
        'Media, mediana y moda',
        'Rango, varianza y desviación estándar',
        'Probabilidad: qué tan posible es algo',
        'Técnicas de conteo: permutaciones y combinaciones',
        'Probabilidad de eventos compuestos',
        'Cómo leer estadísticas en las noticias sin que te engañen',
      ]},
      { titulo: 'Introducción al cálculo', archivo: 'lecciones/matematicas/calculo.js', lecciones: [
        'Límites: acercarse sin llegar',
        'La derivada como razón de cambio',
        'Reglas básicas de derivación',
        'Máximos y mínimos: optimizar',
        'La integral como área',
      ]},
    ],
  },
  {
    id: 'fisica',
    nombre: 'Física',
    descripcion: 'Por qué las cosas se mueven, caen, se calientan, suenan y brillan.',
    color: '#A78BFA',
    unidades: [
      { titulo: 'Bases de la física', lecciones: [
        'Qué es la física y el método científico',
        'Magnitudes y el Sistema Internacional de Unidades',
        'Conversión de unidades',
        'Cifras significativas y errores de medición',
        'Vectores: magnitud y dirección',
      ]},
      { titulo: 'Movimiento (cinemática)', lecciones: [
        'Posición, distancia y desplazamiento',
        'Rapidez y velocidad',
        'Movimiento rectilíneo uniforme',
        'Aceleración y movimiento uniformemente acelerado',
        'Caída libre',
        'Tiro parabólico',
        'Movimiento circular',
      ]},
      { titulo: 'Fuerzas (dinámica)', lecciones: [
        'Qué es una fuerza',
        'Primera ley de Newton: inercia',
        'Segunda ley de Newton: F = m·a',
        'Tercera ley de Newton: acción y reacción',
        'Masa y peso',
        'Fricción',
        'Gravitación universal',
      ]},
      { titulo: 'Trabajo y energía', lecciones: [
        'Trabajo mecánico',
        'Energía cinética y potencial',
        'Conservación de la energía',
        'Potencia',
        'Máquinas simples: palancas y poleas',
        'Cantidad de movimiento y choques',
      ]},
      { titulo: 'Fluidos', lecciones: [
        'Densidad',
        'Presión',
        'Principio de Pascal',
        'Principio de Arquímedes: por qué flotan los barcos',
        'Fluidos en movimiento: principio de Bernoulli',
      ]},
      { titulo: 'Calor y temperatura', lecciones: [
        'Temperatura y escalas',
        'Calor y calor específico',
        'Conducción, convección y radiación',
        'Cambios de estado',
        'Dilatación térmica',
        'Leyes de la termodinámica',
      ]},
      { titulo: 'Ondas, sonido y luz', lecciones: [
        'Qué es una onda',
        'El sonido',
        'Efecto Doppler',
        'Naturaleza de la luz',
        'Reflexión y espejos',
        'Refracción y lentes',
        'El color',
      ]},
      { titulo: 'Electricidad y magnetismo', lecciones: [
        'Carga eléctrica',
        'Ley de Coulomb',
        'Corriente, voltaje y resistencia',
        'Ley de Ohm',
        'Circuitos en serie y en paralelo',
        'Potencia eléctrica y cómo leer tu recibo de luz',
        'Imanes y magnetismo',
        'Electromagnetismo e inducción',
      ]},
      { titulo: 'Física moderna', lecciones: [
        'El átomo y la radiactividad',
        'Introducción a la relatividad',
        'Introducción a la física cuántica',
      ]},
    ],
  },
  {
    id: 'quimica',
    nombre: 'Química',
    descripcion: 'De qué está hecho todo y cómo se transforma.',
    color: '#34D399',
    unidades: [
      { titulo: 'La materia', lecciones: [
        'Qué es la química',
        'Propiedades de la materia',
        'Estados de agregación',
        'Sustancias puras y mezclas',
        'Métodos de separación de mezclas',
        'Cambios físicos y químicos',
      ]},
      { titulo: 'El átomo', lecciones: [
        'Modelos atómicos a través de la historia',
        'Protones, neutrones y electrones',
        'Número atómico y masa atómica',
        'Isótopos',
        'Configuración electrónica',
      ]},
      { titulo: 'La tabla periódica', lecciones: [
        'Cómo está organizada la tabla periódica',
        'Grupos y periodos',
        'Metales, no metales y metaloides',
        'Propiedades periódicas',
      ]},
      { titulo: 'Enlaces químicos', lecciones: [
        'Regla del octeto y estructuras de Lewis',
        'Enlace iónico',
        'Enlace covalente',
        'Enlace metálico',
        'Fuerzas intermoleculares',
      ]},
      { titulo: 'Nomenclatura inorgánica', lecciones: [
        'Óxidos',
        'Hidróxidos',
        'Ácidos',
        'Sales',
      ]},
      { titulo: 'Reacciones químicas', lecciones: [
        'Ecuaciones químicas',
        'Balanceo por tanteo',
        'Tipos de reacciones',
        'Oxidación y reducción',
        'Velocidad de reacción',
      ]},
      { titulo: 'Estequiometría', lecciones: [
        'El mol',
        'Masa molar',
        'Cálculos estequiométricos',
        'Reactivo limitante y rendimiento',
      ]},
      { titulo: 'Disoluciones, ácidos y bases', lecciones: [
        'Soluto y disolvente',
        'Concentración: porcentaje y molaridad',
        'Ácidos y bases',
        'El pH',
      ]},
      { titulo: 'Química orgánica', lecciones: [
        'El carbono, base de la vida',
        'Hidrocarburos',
        'Grupos funcionales',
        'Polímeros y plásticos',
      ]},
      { titulo: 'Química en la vida diaria', lecciones: [
        'La química de los alimentos',
        'Productos de limpieza: cuáles nunca mezclar',
        'Química y medio ambiente',
      ]},
    ],
  },
  {
    id: 'ciencias-naturales',
    nombre: 'Ciencias naturales',
    descripcion: 'Los seres vivos, tu cuerpo, el planeta y el universo.',
    color: '#4ADE80',
    unidades: [
      { titulo: 'Los seres vivos', lecciones: [
        'Qué distingue a un ser vivo',
        'La célula',
        'Célula animal y célula vegetal',
        'Clasificación de los seres vivos',
        'Microorganismos: bacterias, virus y hongos',
      ]},
      { titulo: 'El cuerpo humano', lecciones: [
        'Sistema digestivo',
        'Sistema respiratorio',
        'Sistema circulatorio',
        'Sistema nervioso',
        'Sistema inmunológico y vacunas',
        'Sistema reproductor y sexualidad responsable',
        'Huesos y músculos',
      ]},
      { titulo: 'Salud', lecciones: [
        'Nutrición y alimentación equilibrada',
        'Cómo leer una etiqueta nutricional',
        'Sueño y actividad física',
        'Salud mental',
        'Adicciones',
        'Primeros auxilios básicos',
      ]},
      { titulo: 'Herencia y evolución', lecciones: [
        'ADN, genes y cromosomas',
        'Herencia: las leyes de Mendel',
        'Mutaciones',
        'Evolución y selección natural',
      ]},
      { titulo: 'Ecología', lecciones: [
        'Ecosistemas',
        'Cadenas y redes alimentarias',
        'Ciclos del agua, el carbono y el nitrógeno',
        'Biodiversidad',
        'Contaminación',
        'Cambio climático',
        'Consumo responsable y reciclaje',
      ]},
      { titulo: 'La Tierra', lecciones: [
        'Capas de la Tierra',
        'Placas tectónicas, sismos y volcanes',
        'Rocas y minerales',
        'Atmósfera, clima y tiempo',
        'Qué hacer ante desastres naturales',
      ]},
      { titulo: 'El universo', lecciones: [
        'El sistema solar',
        'Movimientos de la Tierra: días, años y estaciones',
        'Fases de la Luna y eclipses',
        'Estrellas y galaxias',
        'Origen del universo',
      ]},
    ],
  },
  {
    id: 'finanzas-personales',
    nombre: 'Finanzas personales',
    descripcion: 'Cómo administrar tu dinero, ahorrar, evitar deudas malas y hacer crecer lo que tienes.',
    color: '#FBBF24',
    unidades: [
      { titulo: 'Tú y el dinero', lecciones: [
        'Qué es el dinero',
        'Ingresos y gastos',
        'Necesidades y deseos',
        'Cómo leer tu recibo de nómina',
      ]},
      { titulo: 'Presupuesto', lecciones: [
        'Hacer tu primer presupuesto',
        'La regla 50/30/20',
        'Registrar y revisar tus gastos',
        'Gastos hormiga',
      ]},
      { titulo: 'Ahorro', lecciones: [
        'Por qué ahorrar',
        'Fondo de emergencia',
        'Metas de ahorro',
      ]},
      { titulo: 'Interés e inflación', lecciones: [
        'Interés simple',
        'Interés compuesto: la fuerza del tiempo',
        'Inflación: por qué todo sube de precio',
        'Tasa nominal y tasa real',
      ]},
      { titulo: 'Crédito y deudas', lecciones: [
        'Qué es un crédito',
        'Tarjetas de crédito y la trampa del pago mínimo',
        'El costo total de un crédito',
        'Historial crediticio',
        'Cómo comparar préstamos',
        'Salir de deudas: métodos bola de nieve y avalancha',
      ]},
      { titulo: 'Bancos y seguridad', lecciones: [
        'Tipos de cuentas bancarias',
        'Banca en línea y pagos digitales',
        'Fraudes comunes y cómo evitarlos',
        'Esquemas piramidales y promesas de dinero fácil',
      ]},
      { titulo: 'Inversión', lecciones: [
        'Riesgo y rendimiento',
        'Diversificación',
        'Instrumentos de inversión: deuda, fondos y acciones',
        'Invertir a largo plazo',
      ]},
      { titulo: 'Proteger tu futuro', lecciones: [
        'Seguros: para qué sirven',
        'Retiro y pensiones',
        'Impuestos básicos',
        'Grandes compras: auto y vivienda',
      ]},
    ],
  },
  {
    id: 'finanzas',
    nombre: 'Finanzas y economía',
    descripcion: 'Cómo funcionan los mercados, los bancos, las empresas y la economía de un país.',
    color: '#F59E0B',
    unidades: [
      { titulo: 'Conceptos de economía', lecciones: [
        'Escasez y costo de oportunidad',
        'Oferta y demanda',
        'Mercados y formación de precios',
        'Competencia y monopolios',
      ]},
      { titulo: 'El sistema financiero', lecciones: [
        'Breve historia del dinero',
        'Qué hacen los bancos',
        'Bancos centrales y política monetaria',
        'Tasas de interés y su efecto en la economía',
      ]},
      { titulo: 'La economía de un país', lecciones: [
        'Producto Interno Bruto (PIB)',
        'Empleo y desempleo',
        'Crecimiento económico y ciclos',
        'Impuestos y gasto público',
        'Comercio internacional y tipo de cambio',
      ]},
      { titulo: 'Empresas', lecciones: [
        'Qué es una empresa',
        'Ingresos, costos y utilidad',
        'Estados financieros básicos',
        'Punto de equilibrio',
        'Cómo fijar un precio de venta',
      ]},
      { titulo: 'Mercados financieros', lecciones: [
        'Acciones',
        'Bonos',
        'La bolsa de valores',
        'Burbujas y crisis financieras',
      ]},
      { titulo: 'Emprender', lecciones: [
        'De la idea al negocio',
        'Modelo de negocio',
        'Finanzas de un pequeño negocio',
      ]},
    ],
  },
  {
    id: 'ofimatica',
    nombre: 'Ofimática',
    descripcion: 'Usar la computadora, documentos, hojas de cálculo y presentaciones con confianza.',
    color: '#38BDF8',
    unidades: [
      { titulo: 'La computadora', lecciones: [
        'Partes de una computadora',
        'El sistema operativo',
        'Archivos y carpetas',
        'Atajos de teclado esenciales',
        'Internet y el navegador',
        'Correo electrónico',
        'Seguridad digital: contraseñas y fraudes en línea',
      ]},
      { titulo: 'Procesador de textos', lecciones: [
        'Crear, guardar y abrir documentos',
        'Formato de texto y de párrafo',
        'Estilos y títulos',
        'Listas y tablas',
        'Imágenes en el documento',
        'Encabezados, pies de página y numeración',
        'Índice automático',
        'Ortografía, comentarios y control de cambios',
        'Exportar a PDF e imprimir',
      ]},
      { titulo: 'Hojas de cálculo', lecciones: [
        'Celdas, filas y columnas',
        'Tipos de datos',
        'Fórmulas básicas',
        'Referencias relativas y absolutas',
        'Funciones: SUMA, PROMEDIO, MIN, MAX y CONTAR',
        'La función SI',
        'Buscar datos: BUSCARV y BUSCARX',
        'Ordenar y filtrar',
        'Formato condicional',
        'Gráficos',
        'Tablas dinámicas',
        'Proyecto: tu presupuesto personal en una hoja de cálculo',
      ]},
      { titulo: 'Presentaciones', lecciones: [
        'Diseño de diapositivas',
        'Menos texto, más ideas',
        'Imágenes y gráficos en presentaciones',
        'Cómo presentar en público',
      ]},
      { titulo: 'Trabajo en la nube', lecciones: [
        'Almacenamiento en la nube',
        'Documentos compartidos y colaboración',
        'Videollamadas',
      ]},
    ],
  },
  {
    id: 'lectura',
    nombre: 'Lectura',
    descripcion: 'Entender lo que lees, pensar críticamente y escribir con claridad.',
    color: '#F472B6',
    unidades: [
      { titulo: 'Fundamentos', lecciones: [
        'Por qué leer',
        'Cómo crear el hábito de la lectura',
        'Tipos de texto: narrativo, expositivo, argumentativo e instructivo',
      ]},
      { titulo: 'Comprensión lectora', lecciones: [
        'Idea principal e ideas secundarias',
        'Deducir palabras por el contexto',
        'Inferencias: leer entre líneas',
        'Hacer un resumen',
        'Mapas conceptuales',
      ]},
      { titulo: 'Pensamiento crítico', lecciones: [
        'Hechos y opiniones',
        'La intención del autor',
        'Cómo se construye un argumento',
        'Falacias comunes',
        'Sesgos cognitivos',
        'Verificar noticias y detectar desinformación',
      ]},
      { titulo: 'Lectura práctica', lecciones: [
        'Leer instructivos y manuales',
        'Leer contratos y letras pequeñas',
        'Leer gráficas e infografías',
        'Lectura rápida y escaneo',
      ]},
      { titulo: 'Literatura', lecciones: [
        'Géneros literarios',
        'Elementos de la narración',
        'Figuras retóricas',
        'Poesía',
        'Teatro',
      ]},
      { titulo: 'Escribir con claridad', lecciones: [
        'Estructura de un texto',
        'Acentuación',
        'Puntuación',
        'Escribir un resumen',
        'Escribir un ensayo argumentativo',
      ]},
    ],
  },
  {
    id: 'ia',
    nombre: 'Inteligencia artificial',
    descripcion: 'Qué es la IA, cómo funcionan los modelos de lenguaje y cómo usarlos con criterio.',
    color: '#22D3EE',
    unidades: [
      { titulo: 'Qué es la IA', lecciones: [
        'Qué es la inteligencia artificial',
        'Breve historia de la IA',
        'La IA en tu vida diaria',
      ]},
      { titulo: 'Cómo aprenden las máquinas', lecciones: [
        'Los datos',
        'Aprendizaje automático',
        'Redes neuronales explicadas sin fórmulas',
        'Entrenar y evaluar un modelo',
      ]},
      { titulo: 'Modelos de lenguaje (LLMs)', lecciones: [
        'Qué es un modelo de lenguaje',
        'Tokens: cómo "lee" un LLM',
        'Cómo genera texto: predecir la siguiente palabra',
        'Contexto y memoria',
        'Alucinaciones: cuando la IA inventa',
        'Qué puede y qué no puede hacer',
      ]},
      { titulo: 'Usar la IA bien', lecciones: [
        'Escribir instrucciones claras',
        'Dar contexto y ejemplos',
        'Verificar lo que te responde',
        'Usar IA para estudiar sin hacer trampa',
      ]},
      { titulo: 'IA y sociedad', lecciones: [
        'Sesgos en la IA',
        'Privacidad: qué no compartir',
        'Deepfakes y contenido falso',
        'Derechos de autor',
        'IA y el futuro del trabajo',
        'Impacto ambiental de la IA',
      ]},
    ],
  },
  {
    // Niveles según el Marco Común Europeo de Referencia (MCER): A1, A2 y B1.
    id: 'ingles',
    nombre: 'Inglés',
    descripcion: 'Del primer "hello" a conversar, leer y escribir con soltura: niveles A1, A2 y B1.',
    color: '#FB923C',
    unidades: [
      { titulo: 'A1 · Primeros pasos', lecciones: [
        'El alfabeto y la pronunciación',
        'Saludos y presentaciones',
        'Números',
        'El verbo to be',
        'Pronombres personales',
        'Artículos: a, an y the',
        'Plurales',
      ]},
      { titulo: 'A1 · Mi mundo', lecciones: [
        'La familia y los posesivos (my, your, \'s)',
        'This, that, these y those',
        'There is y there are',
        'Preposiciones de lugar',
        'Colores y adjetivos',
        'La casa y los objetos cotidianos',
      ]},
      { titulo: 'A1 · Mi día', lecciones: [
        'Presente simple',
        'Preguntas y negaciones con do y does',
        'La hora y la rutina diaria',
        'Días, meses y fechas',
        'Adverbios de frecuencia',
        'Preguntas con what, where, when, who, why y how',
      ]},
      { titulo: 'A1 · Lo que necesito', lecciones: [
        'Comida y bebida',
        'Contables e incontables: some y any',
        'De compras: how much y how many',
        'Can: habilidad y permiso',
        'Presente continuo',
        'Pedir y dar direcciones',
      ]},
      { titulo: 'A2 · Hablar del pasado', lecciones: [
        'Pasado del verbo to be',
        'Pasado simple: verbos regulares',
        'Pasado simple: verbos irregulares',
        'Preguntas y negaciones en pasado',
        'Contar una historia: first, then, after that',
        'Pasado continuo',
      ]},
      { titulo: 'A2 · Describir y comparar', lecciones: [
        'Comparativos',
        'Superlativos',
        'Describir personas',
        'La ropa y el clima',
        'Pronombres de objeto: me, him, her, them',
      ]},
      { titulo: 'A2 · Planes y futuro', lecciones: [
        'Going to',
        'Will',
        'Presente continuo para planes',
        'Hacer invitaciones y responderlas',
      ]},
      { titulo: 'A2 · Vida práctica', lecciones: [
        'Viajes y transporte',
        'En el restaurante',
        'En el médico',
        'Obligación y consejo: must, have to y should',
        'Escribir un correo informal',
      ]},
      { titulo: 'B1 · Experiencias', lecciones: [
        'Presente perfecto',
        'Ever, never, already y yet',
        'For y since',
        'Presente perfecto o pasado simple',
        'Used to',
        'Pasado perfecto',
      ]},
      { titulo: 'B1 · Posibilidades', lecciones: [
        'Condicional cero y primer condicional',
        'Segundo condicional',
        'Might, may y could',
        'Gerundio o infinitivo',
      ]},
      { titulo: 'B1 · Estructuras clave', lecciones: [
        'Voz pasiva',
        'Estilo indirecto: contar lo que alguien dijo',
        'Oraciones de relativo: who, which y that',
        'Phrasal verbs más comunes',
      ]},
      { titulo: 'B1 · Comunicarte en el mundo real', lecciones: [
        'Dar opiniones y argumentar',
        'Escribir un correo formal',
        'Llamadas telefónicas',
        'Entrevista de trabajo',
        'Entender noticias y podcasts',
      ]},
    ],
  },
  {
    // Nivel elemental de HSK 3.0 (estándar de 2021): niveles 1, 2 y 3.
    // Metas acumuladas: N1 300 caracteres / 500 palabras; N2 600 / 1272; N3 900 / 2245.
    id: 'mandarin',
    nombre: 'Mandarín',
    descripcion: 'Pinyin, tonos, caracteres y conversación básica: nivel elemental del nuevo HSK (niveles 1 a 3).',
    color: '#F87171',
    unidades: [
      { titulo: 'HSK 1 · Sonidos y escritura', lecciones: [
        'Qué es el mandarín y cómo se escribe',
        'Pinyin: iniciales',
        'Pinyin: finales',
        'Los cuatro tonos y el tono neutro',
        'Cambios de tono: el tercer tono, 不 y 一',
        'Trazos y orden de trazos',
        'Radicales: las piezas de los caracteres',
      ]},
      { titulo: 'HSK 1 · Primeras frases', lecciones: [
        'Saludar: 你好',
        'Presentarte: 我叫…',
        'Pronombres personales',
        'Números del 0 al 100',
        'El verbo 是',
        'Preguntas con 吗',
        'Negar con 不',
        'Posesión con 的',
      ]},
      { titulo: 'HSK 1 · Vida diaria', lecciones: [
        'La familia',
        'Fechas y días de la semana',
        'La hora',
        'Tener: 有 y 没有',
        'Clasificadores: 个 y otros',
        'Preguntar cantidades: 几 y 多少',
        'Dónde está algo: 在',
        'Comprar: 多少钱',
        'Comida y bebida: 想 y 要',
      ]},
      { titulo: 'HSK 2 · Gramática', lecciones: [
        'Acción terminada: 了',
        'Experiencias: 过',
        'Acción en curso: 在 y 正在',
        'Poder y saber: 会, 能 y 可以',
        'Comparar con 比',
        'Elegir: 还是 y 或者',
        'Causa y efecto: 因为…所以…',
        'Algo está por pasar: 要…了',
        'Complemento de grado: 得',
      ]},
      { titulo: 'HSK 2 · Situaciones', lecciones: [
        'Transporte y direcciones',
        'El clima',
        'En la tienda',
        'En el médico',
        'Pasatiempos',
        'Hablar por teléfono',
      ]},
      { titulo: 'HSK 3 · Gramática', lecciones: [
        'Complementos de resultado',
        'Complementos de dirección',
        'La estructura 把',
        'La voz pasiva con 被',
        'Aunque: 虽然…但是…',
        'Si…entonces: 如果…就…',
        'Dos acciones a la vez: 一边…一边…',
        'Cada vez más: 越来越',
        'Incluso: 连…都…',
      ]},
      { titulo: 'HSK 3 · Comunicación', lecciones: [
        'La escuela y el trabajo',
        'Planear un viaje',
        'Festividades y cultura china',
        'Leer textos cortos',
        'Escribir mensajes cortos en caracteres',
      ]},
    ],
  },
];
