// Textos de la interfaz. Para un nuevo idioma: copiar como textos.<idioma>.js y traducir.
window.TEXTOS = {
  marca: 'Free Learning',
  lema: 'Aprende lo esencial, gratis y para siempre.',
  intro: 'Matemáticas, ciencias, finanzas, computación, lectura, inglés y mandarín explicados de forma simple, con ejercicios para practicar en el momento. Sin cuentas, sin anuncios, sin internet una vez descargado.',
  navMaterias: 'Materias',
  navComoUsar: 'Cómo usar',
  descargar: 'Descargar sitio (.zip)',
  volver: 'Todas las materias',
  unidad: 'Unidad',
  lecciones: 'lecciones',
  completadas: 'completadas',
  proximamente: 'Próximamente',
  reiniciar: 'Reiniciar mi progreso',
  confirmarReinicio: '¿Seguro que quieres borrar todo tu progreso? Esto no se puede deshacer.',
  reiniciado: 'Tu progreso se borró.',
  pie: 'Hecho con cariño para quien quiera aprender. Libre y gratuito para siempre.',
  progresoLocal: 'Tu progreso se guarda solo en este navegador y en este dispositivo.',
  noEncontrado: 'No encontramos esta página.',
  // Lecciones
  objetivo: 'Al terminar podrás…',
  explicacion: 'Explicación',
  ejemplo: 'Ejemplo resuelto',
  vidaReal: '¿Para qué sirve en la vida real?',
  practica: 'Practica',
  practicaIntro: 'Resuelve cada ejercicio. Si te atoras, pide una pista; después de un intento puedes ver la solución.',
  fuentes: 'Fuentes',
  imprimir: 'Imprimir o guardar PDF',
  leccionHecha: 'Completada',
  leccionPendiente: 'Esta lección todavía está en preparación.',
  anterior: 'Anterior',
  siguiente: 'Siguiente',
  navLecciones: 'Navegación entre lecciones',
  felicidades: '¡Lección completada! Tu progreso quedó guardado.',
  // Ejercicios
  ejercicio: 'Ejercicio',
  tuRespuesta: 'Tu respuesta',
  comprobar: 'Comprobar',
  verPista: 'Ver pista',
  verSolucion: 'Ver solución',
  correcto: '¡Correcto!',
  incorrecto: 'Todavía no. Revisa tu procedimiento e inténtalo otra vez.',
  escribeRespuesta: 'Escribe o elige una respuesta primero.',
  solucionDisponible: 'Si quieres, ya puedes ver la solución.',
  faltaSimplificar: 'Vas bien: tu expresión es equivalente, pero todavía se puede simplificar o desarrollar más.',
  ayudaExpresion: 'Usa ^ para potencias (x^2) y * o nada para multiplicar (3x, 2(x+1)).',
  comoUsarTitulo: 'Cómo usar Free Learning en tu computadora',
  comoUsarIntro: 'Puedes guardar este sitio completo en tu computadora y usarlo sin internet. No necesitas instalar nada: solo un navegador (Chrome, Firefox, Edge o Safari).',
  comoUsarPasos: [
    ['Descarga el sitio', 'Pulsa el botón <strong>Descargar sitio (.zip)</strong>. Se guardará un archivo llamado <code>free-learning.zip</code>, normalmente en tu carpeta de Descargas.'],
    ['Descomprime el archivo', '<strong>Windows:</strong> clic derecho sobre el archivo y elige <em>Extraer todo</em>. <strong>Mac:</strong> doble clic sobre el archivo. <strong>Linux:</strong> clic derecho y <em>Extraer aquí</em>.'],
    ['Abre el sitio', 'Entra a la carpeta <code>free-learning</code> y haz doble clic en el archivo <code>index.html</code>. Se abrirá en tu navegador y listo: ya puedes aprender.'],
    ['Guárdalo para volver rápido', 'Con el sitio abierto, presiona <kbd>Ctrl</kbd> + <kbd>D</kbd> (o <kbd>⌘</kbd> + <kbd>D</kbd> en Mac) para guardarlo en tus marcadores.'],
  ],
  comoUsarNotasTitulo: 'Bueno saber',
  comoUsarNotas: [
    'Funciona sin internet: todo lo necesario viene dentro de la carpeta.',
    'Tu progreso se guarda en el navegador que uses. Si cambias de navegador o borras los datos de navegación, empezará desde cero.',
    'No muevas ni borres archivos de la carpeta; si lo haces, descarga el .zip de nuevo.',
    'En teléfono también funciona, pero abrir archivos locales depende de cada modelo. En computadora es más sencillo.',
    'Puedes copiar la carpeta a una memoria USB y compartirla con quien quieras. Es libre.',
  ],
};
